# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-win
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - data:
        - key: DB-HOST
          objectName: DB-HOST # name of the mounted content to sync. this could be the object name or object alias
        - key: DB-NAME
          objectName: DB-NAME
        - key: DB-PASSWORD
          objectName: DB-PASSWORD
        - key: DB-PORT
          objectName: DB-PORT
        - key: DB-USER
          objectName: DB-USER
      secretName: akvsecretscertwin
      type: Opaque

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<managed identity-client id>" #assign identity client_id
    keyvaultName: <keyvault-name> # the name of the KeyVault
    cloudName: AzurePublicCloud # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: DBHost
          objectAlias: DB-HOST
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBName
          objectAlias: DB-NAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBPassword
          objectAlias: DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBPort
          objectAlias: DB-PORT
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBUser
          objectAlias: DB-USER
          objectType: secret
          objectVersion: ""
    resourceGroup: "<resourcegroup-name>" #provide azure key vault resourceGroup
    subscriptionId: "<subscriptionID> " # subscriptionId
    tenantId: "<tenantID>" # TenantId