# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poll-azurefile-share
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi