# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-win
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - data:
        - key: CATALOG_DB_CONTEXT
          objectName: CATALOG_DB_CONTEXT # name of the mounted content to sync. this could be the object name or object alias
        - key: STORAGE_CONNECTION_STRING
          objectName: STORAGE_CONNECTION_STRING     
      secretName: akvsecretscertwin
      type: Opaque

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<enter client ID>" #assign identity client_id
    keyvaultName: <enter key-vault name> # the name of the KeyVault
    cloudName: AzurePublicCloud # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: CatalogDBContext
          objectAlias: CATALOG_DB_CONTEXT
          objectType: secret
          objectVersion: ""
        - |
          objectName: StorageConnectionString
          objectAlias: STORAGE_CONNECTION_STRING
          objectType: secret
          objectVersion: ""       
          
    resourceGroup: "<ResourceGroup>" #provide azure key vault resourceGroup
    subscriptionId: "<subscriptionId>" # subscriptionId
    tenantId: "<TenantId>" # TenantId
    