apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname-win
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - data:
        - key: TICKET_DESK_SECURITY_CONNECTION_STRING
          objectName: TICKET_DESK_SECURITY_CONNECTION_STRING # name of the mounted content to sync. this could be the object name or object alias
        - key: TICKET_DESK_ENTITIES
          objectName: TICKET_DESK_ENTITIES
        - key: ELMAH_LOG
          objectName: ELMAH_LOG
      secretName: akvsecretscertwin
      type: Opaque

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "cf1865b9-3390-4880-8d18-07d1b08f2d4b" #provide your cluster managed indentity's client_id you can find it on azure portol
    keyvaultName: ticketdeskkeyvault1201 # the name of the KeyVault
    cloudName: AzurePublicCloud # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: TicketDeskSecurityConnectionString
          objectAlias: TICKET_DESK_SECURITY_CONNECTION_STRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: TicketDeskEntities
          objectAlias: TICKET_DESK_ENTITIES
          objectType: secret
          objectVersion: ""
        - |
          objectName: ElmahLog
          objectAlias: ELMAH_LOG
          objectType: secret
          objectVersion: ""
    resourceGroup: "my-win-container-RGS" #provide azure key vault resourceGroup
    subscriptionId: "233f533c-1d3f-4ec4-9c49-c7*********" # subscriptionId
    tenantId: "fa0fd8d2-d414-482c-a2a3-d**********" # TenantId